### ISSUE TITLE
Enable notifications by default

### ISSUE THREAD

**Issue by bdaley** [GreenhouseStudios/sourcery-web-app#115]

**Comment by briankelleher** [comment]
Is there additional context on this? Referring to email notifications to institutions receiving requests or in-app notifications?

**Comment by bdaley** [comment]
Maybe @samsonweiner can help me fill in the gaps here, but the default state for the preference of whether or not to receive notifications (on a new user) is set to false. Or, at the very least, assumed to be false/blank.

Notifications are sent for changes in the status of a request, like: pending, picked up, complete, etc.

I believe we decided that it was best for new accounts to receive notifications by default. However, I don't recall exactly which notifications we're talking about here, since this bug is a little old. I know that we ruled out push notifications due to incompatibility with Safari/iOS. I _think_ this might be referencing email notifications, but hopefully @samsonweiner can correct me if I'm wrong.

**Comment by briankelleher** [comment]
OK.

So, I'm guessing that part of this includes changing this function, which right now looks like it's written to notify sorcerers based on their location (or last location).   I propose that this instead finds any repository/organization owners and notifies them with an email.

Do we think this has any impact on their selected 'Notification' preference in the settings?  It isn't the same functionality, and is now business critical (kind of how I can unsubscribe from Twitter marketing or suggestions but if something happens directly to my account I always get an email).

If we agree, I think we should hide the 'notifications' toggle in settings.
