### ISSUE TITLE
Configure local environment for use with Firebase Emulator

### ISSUE THREAD

**Issue by bdaley** [GreenhouseStudios/sourcery-web-app#138]
When running the app locally, connections are made to the sourcery-dev database and sourcery-dev functions. But this makes the testing of any functions extremely difficult, if not impossible.

In order to properly test functions before deployment, we need to utilize both the firestore and functions emulators. We also need to instruct our app to use the emulators running locally, rather than on the sourcery-dev account.

https://firebase.google.com/docs/emulator-suite/connect_and_prototype?database=Firestore

**Comment by briankelleher** [comment]
Resolved now? The emulators seem to work and I made small config changes at some point to detect emulation on functions.

**Comment by bdaley** [comment]
Yeah - I think we just forgot to tie it to a PR.
