### ISSUE TITLE
Request Disappears after Adding Card

### ISSUE THREAD

**Issue by whamrick** [GreenhouseStudios/sourcery-web-app#159]
I went through the screens to submit a request, got to the last screen and couldn't click submit because I hadn't added a card for the account.

After I added the card, I was left on the Manage Payments page, but had no way to get back to the request I had just filled out (but hadn't submitted yet).

**Comment by briankelleher** [comment]
This should be completed now also, @bdaley .  Cards are no longer required to make requests in the UI, and there is no cloud func/firestore restrictions on users without cards.  I believe this commit solved that: https://github.com/GreenhouseStudios/sourcery-web-app/commit/bb752c2b34c066b67b695ceb5206677ebaecede7
