### ISSUE TITLE
Remove Ratings

### ISSUE THREAD

**Issue by bdaley** [GreenhouseStudios/sourcery-web-app#217]
Temporarily remove the rating system as we focus our efforts on the institutional version of the app.

**Comment by briankelleher** [comment]
Should I comment out the rating services in the request references for now in repo, and we can just keep the data the way it is?  And of course, remove the UI pieces that correspond.  If you want to go further in ripping this out, let me know, I can help remove from firestore/delete references from vuex store, ratings view, and terms/conditions.

**Comment by bdaley** [comment]
It will be back again at some point, so I would just comment out the UI pieces or any textual references to the concept of a "ratings" system. This was something that @samsonweiner worked on, so he can probably assist you in what to look for (if needed). At the time, we considered utilizing ratings in the pricing algorithm. It's just not necessary at the moment.
