### ISSUE TITLE
Fix Vuetify Errors

### ISSUE THREAD

**Issue by bdaley** [GreenhouseStudios/sourcery-web-app#225]

**Comment by bdaley** [comment]
![](https://user-images.githubusercontent.com/382814/119398497-a5125580-bca5-11eb-982b-55ffae86800d.png)

**Comment by bdaley** [comment]
@mueller-alex Let me know if you can tackle this one.

**Comment by mueller-alex** [comment]
With the upgrade they changed `v-list-item-sub-title` to `v-list-item-subtitle`, guess I missed a few.

**Comment by bdaley** [comment]
No worries. There were A LOT of changes in your PR. I'm sure we've missed other stuff too. I just wanted to get everyone working off of your code, rather than the old design.
