### ISSUE TITLE
Develop native Android application

### ISSUE THREAD

**Issue by carly322** [GreenhouseStudios/sourcery-web-app#311]
TODO:

- [x] #366 
- [x] #367 
- [x] Add /assetlinks.json https://docs.pwabuilder.com/#/builder/android?id=publish

**Comment by bdaley** [comment]
Removed "iOS and" from the title. Won't be going with iOS just yet.

**Comment by bdaley** [comment]
Waiting on the app review from Google...

**Comment by bdaley** [comment]
https://play.google.com/store/apps/details?id=org.sourcery
