### ISSUE TITLE
Allow users to REQUEST deletion of their account and associated data

### ISSUE THREAD

**Issue by bdaley** [GreenhouseStudios/sourcery-web-app#366]
This can simply be a form that gets routed to email for now. (Maybe on the account/settings page?) We just need a URL that meets the requirements listed in the [Google Play Console](https://play.google.com/console/u/0/developers/5068098061129750044/app/4973430179683629256/app-content/data-privacy-security?source=dashboard):

**This link will be shown on your Google Play store listing, and should:**

- refer to your app or developer name that is shown on your store listing

- prominently feature the steps that users should take to request that their account is deleted

- specify the types of data that are deleted or kept, and any additional retention period

**Comment by briankelleher** [comment]
https://sourceryapp.org/privacy

This should cover all items mentioned in the Google Play Store policy about data retention and collection.  Page outlines that information and how to REQUEST deletion.

**Comment by bdaley** [comment]
lgtm
