### ISSUE TITLE
Research and describe 3-5 possible promotional/how-to videos

### ISSUE THREAD

**Issue by foundhistory** [GreenhouseStudios/sourcery-web-app#411]

**Comment by ravenmariemorris** [comment]
[Sourcery App-Promotional and How To Videos-Research and Brainstorm Document.docx](https://github.com/GreenhouseStudios/sourcery-web-app/files/12883354/Sourcery.App-Promotional.and.How.To.Videos-Research.and.Brainstorm.Document.docx)

**Comment by ravenmariemorris** [comment]
The document linked above describes five possible promotional and how-to videos for the Sourcery website. 

I think the next step is to hand this project off to someone with a design-oriented background who knows storyboarding and 2D animation. This person can work directly with the new hire to develop these five videos. I (Raven) volunteer to act as a consultant on this project going forward.

**Comment by foundhistory** [comment]
Moved to Basecamp
