### ISSUE TITLE
Bookmarklet to Create Request

### ISSUE THREAD

**Issue by briankelleher** [GreenhouseStudios/sourcery-web-app#449]
This might be impacted by changes to the Create Request screen (removing repository) but not by much.

**Comment by bdaley** [comment]
@briankelleher Do you/we have a good list of institutions with web-based search that I could use for testing? This bookmarklet tool will obviously need to be flexible enough to work on any web page, but I'm guessing there are certain platforms that would make the data extraction or scrapping easier than others.

**Comment by briankelleher** [comment]
I don't have any particular list based on their web search capabilities (with more time I should poke around more...), but we do have the existing list from prior to B2B still loaded in the repository table.  Perhaps the best method is to take 1-2 partners and a few random from the table?

**Comment by briankelleher** [comment]
@bdaley free to close unless you want to track other changes here!
